version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Install dependencies in virtual environment
          command: |
            virtualenv ~/venv
            source ~/venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: |
            source ~/venv/bin/activate
            mkdir test-results
            python -m pytest -v --junitxml=test-results/junit.xml
      - store_test_results:
              path: test-results
      - store_artifacts:
              path: test-results
