version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          name: Install dependencies in virtual environment
          command: |
            virtualenv ~/venv
            source ~/venv/bin/activate
            pip install -r requirements-dev.txt
            pip install coverage-badge
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "~/venv"
      - run:
          name: Run unit tests
          command: |
            source ~/venv/bin/activate
            mkdir test-results
            python -m pytest -v --junitxml=test-results/junit.xml --cov=. \
            --cov-report=term --cov-report=html --cov-branch
            coverage-badge -o coverage.svg
      - store_test_results:
              path: test-results
      - store_artifacts:
              path: htmlcov
      - store_artifacts:
              path: coverage.svg

workflows:
  commit:
    jobs:
      - build
  scheduled:
    triggers:
      - schedule:
          cron: "20,30 * * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
